### ISSUE TITLE
Menu bar 

### ISSUE THREAD

**Issue by kermit-xrp** [EnclaviaLabs/XLS_NFT_Explorer#1]
Maybe for clearer and common look (with reward tool) consider moving the menu bar to the top. Just a suggestion.

**Comment by kermit-xrp** [comment]
Doubled menu bar - Side one and bottom one. Maybe keep just one option to save the space?

**Comment by EnclaviaLabs** [comment]
> Doubled menu bar - Side one and bottom one. Maybe keep just one option to save the space?

It has just been shipped. The main menu and screen titles are moved to the top, while the main 3 tabs are down the bottom
